// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-J-d0Xk_xjEFrwE67jrDYeZA6uG04CB8',
    appId: '1:838925430468:web:81953f3aaacef527182391',
    messagingSenderId: '838925430468',
    projectId: 'sazedar-admin-45cfb',
    authDomain: 'sazedar-admin-45cfb.firebaseapp.com',
    storageBucket: 'sazedar-admin-45cfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4iIKc4h_fz7VEXqJ4x3U68eMwwE8FrVM',
    appId: '1:838925430468:android:b2a80766566d4574182391',
    messagingSenderId: '838925430468',
    projectId: 'sazedar-admin-45cfb',
    storageBucket: 'sazedar-admin-45cfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0vGsa_y7ySvBsEjyJj8fUnXOBjTtwLIs',
    appId: '1:838925430468:ios:88b05778439baa2a182391',
    messagingSenderId: '838925430468',
    projectId: 'sazedar-admin-45cfb',
    storageBucket: 'sazedar-admin-45cfb.firebasestorage.app',
    iosBundleId: 'com.sazedar.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0vGsa_y7ySvBsEjyJj8fUnXOBjTtwLIs',
    appId: '1:838925430468:ios:97bd3b4f292b6d39182391',
    messagingSenderId: '838925430468',
    projectId: 'sazedar-admin-45cfb',
    storageBucket: 'sazedar-admin-45cfb.firebasestorage.app',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-J-d0Xk_xjEFrwE67jrDYeZA6uG04CB8',
    appId: '1:838925430468:web:643dd5f212e69ef0182391',
    messagingSenderId: '838925430468',
    projectId: 'sazedar-admin-45cfb',
    authDomain: 'sazedar-admin-45cfb.firebaseapp.com',
    storageBucket: 'sazedar-admin-45cfb.firebasestorage.app',
  );
}
